# company_list['twilio'] = {'name':'Twilio', "description":"Twilio is a cloud communications (IaaS) company based in San Francisco, California. Twilio allows software developers to programmatically make and receive phone calls and send and receive text messages using its web service APIs. Twilio's services are accessed over HTTP and are billed based on usage.", 'links':"https://boards.greenhouse.io/twilio/jobs/26688#app"}
company_list['counsyl'] = {'name':'Counsyl', "description":"Counsyl is a technology company that strives to give millions of men and women access to vital information about their bodies so they can confidently make choices about their lives. Counsyl integrates sophisticated technology with custom automation in its CLIA-certified, CAP-accredited and NYS CLEP-permitted medical laboratory.", 'links':"https://www.counsyl.com/careers/software-engineering-intern-2015/"}
# company_list['dropbox'] = {'name':'Dropbox', "description":"Dropbox is a file hosting service operated by Dropbox, Inc., headquartered in San Francisco, California, that offers cloud storage, file synchronization, personal cloud, and client software. Dropbox allows users to create a special folder on their computers, which Dropbox then synchronizes so that it appears to be the same folder (with the same contents) regardless of which computer is used to view it. Files placed in this folder are accessible via the folder, or through the DropBox website and a mobile app.", 'links':"https://www.dropbox.com/jobs/apply/544"}
# company_list['groupon'] = {'name':'Groupon', "description":"Groupon is a deal-of-the-day website that features discounted gift certificates usable at local or national companies. Groupon was launched in November 2008, and the first market for Groupon was Chicago, followed soon thereafter by Boston, New York City, and Toronto.", 'links':"https://jobs.groupon.com/careers/university-internships/software-development-engineering-intern-summer-2015-san-francisco-ca-united-states-7784/apply/"}
# company_list['fivestars'] = {'name':'FiveStars', "description":"FiveStars is the fastest growing company in customer loyalty and marketing automation for local businesses. Launched out of Y-Combinator three years ago to democratize Fortune 500-level loyalty technology, we now drive two million customer visits per month across our network of over five thousand businesses and have raised a total of $45 million in funding from top-tier investors like Menlo Ventures, Lightspeed Venture Partners, and DCM.", 'links':"http://www.fivestars.com/team/careers/?gh_jid=33436"}
# company_list['stripe'] = {'name':'Stripe', "description":"Stripe is a company that provides a way for individuals and businesses to accept payments over the Internet. Co-founded by brothers Patrick and John Collison, the company has received $130 million in funding; investors include Sequoia Capital, General Catalyst Partners, Andreessen Horowitz, Founders Fund, Khosla Ventures, and PayPal co-founders Peter Thiel, Max Levchin, and Elon Musk.", 'links':"https://stripe.com/jobs/positions/engineer/#engineering"}
# company_list['arista'] = {'name':'Arista', "description":"Arista Networks (previously Arastra) is a computer networking company headquartered in Santa Clara, California, USA. The company designs and sells multilayer network switches to deliver software-defined networking (SDN) solutions for large datacenter, cloud computing, high-performance computing and high-frequency trading environments.", 'links':"http://www.arista.com/en/careers/engineering"}
# company_list['godaddy'] = {'name':'GoDaddy', "description":"Go Daddy is a privately held company that is primarily an internet domain registrar and web hosting company.", 'links':"https://hire.jobvite.com/CompanyJobs/Careers.aspx?c=qCH9Vfw7&jvprefix=https%3a%2f%2fwww.godaddy.com&cs=9jTaVfw1&jvresize=%2fJobs%2fFrameResize.html&page=Apply&j=oKEAZfwH"}
# company_list['meraki'] = {'name':'Meraki', "description":"Meraki was a company that provided products for large-scale, distributed wired and wireless networks. The company was started by two MIT PhD students, Sanjit Biswas and John Bicket, along with Hans Robertson. The company was based in part on the MIT Roofnet project and became part of Cisco Systems in December 2012.", 'links':"https://meraki.cisco.com/jobs#27738"}
# company_list['liveramp'] = {'name':'Liveramp', "description":"LiveRamp believes in the power of connected data. We unify customer data across disparate applications, enabling a new generation of marketing tools. Our goal is to empower brands to seamlessly leverage their marketing data to delight customers with relevant and singular experiences.", 'links':"http://liveramp.com/careers/careers-public-static-final-intern-software-engineer-summer-2015/"}
# company_list['kabam'] = {'name':'Kabam', "description":"Kabam (formerly Watercooler, Inc.) is an interactive entertainment company that develops and publishes massively multiplayer social games (MMSG’s), including Dragons of Atlantis: Heirs of the Dragon and Kingdoms of Camelot. Before expanding into gaming, Kabam established itself as a social applications developer with entertainment and sports communities totaling more than 60 million users.", 'links':"http://hire.jobvite.com/CompanyJobs/Careers.aspx?k=Apply&c=qE09Vfws&j=o96lZfwj"}
# company_list['indiegogo'] = {'name':'Indiegogo', "description":"Indiegogo is an international crowdfunding site founded by Danae Ringelmann, Slava Rubin, and Eric Schell in 2008. Its headquarters are in San Francisco, California. The site was founded in 2008 and was one of the first sites to offer crowd funding. Indiegogo allows people to solicit funds for an idea, charity or start-up business. The site’s goal is to empower anyone that has an idea to be able to raise the funds and amplify their goal. Nine million people from all around the world visit the site on a monthly basis.", 'links':"https://www.indiegogo.com/careers?jvi=oSrhZfwj,Job"}
company_list['palantir'] = {'name':'Palantir', 'description': 'Palantir Technologies, Inc. is an American computer software and services company, specializing in data analysis. Primary clients are the US government customers, and since 2010, financial customers.', 'links': 'https://www.palantir.com/careers/OpenPosApply?id=a0m80000000jYdb'}
# company_list['riot'] = {'name': 'Riot Games', 'description':'Riot Games is an American-based Chinese-owned video game publisher that was established in 2006. Their main office is based in Santa Monica, California.Riot has produced a single game, League of Legends, which was released in both North America and Europe on October 27, 2009.','links':'https://boards.greenhouse.io/riotgames/jobs/10838#app'}
# company_list['pinterest'] = {'name':'Pinterest', 'description':'Pinterest is a web and mobile application company that offers a visual discovery, collection, sharing, and storage tool. Users create and share the collections of visual bookmarks (boards). ','links':'https://about.pinterest.com/en/careers/cloud-software-engineer-intern_34498'}
# company_list['evernote'] ={'name': 'Evernote','description': 'Evernote is a suite of software and services, designed for notetaking and archiving.','links':'https://evernote.com/careers/job/?id=26620?gh_jid=26620'}
company_list['affirm'] = {'name': 'Affirm', 'description' : 'Affirm lets shoppers pay for purchases across multiple months with transparent, fairly-priced fees built into every payment, and boosts conversion and basket size for eTailers at less than the cost of credit cards.','links': 'https://jobs.lever.co/affirm/41093734-0492-4f7e-b5ab-7fe53f2143e7/apply'}
# company_list['surveymonkey'] = {'name':'SurveyMonkey','description':'SurveyMonkey provides free, customizable surveys, as well as a suite of paid back-end programs.','links':'https://boards.greenhouse.io/surveymonkey/jobs/30035?#app'}
company_list['quora'] = {'name':'Quora','description':'Quora is a question-and-answer website where questions are created, answered, edited and organized by its community of users','links':'https://jobs.lever.co/quora/c6456987-4af5-4db0-984e-b8489ffdcf0a/apply'}
# company_list['snapchat'] = {'name':'Snapchat','description':'Snapchat is a photo messaging application.Using the application, users can take photos, record videos, add text and drawings, and send them to a controlled list of recipients.','links':'https://boards.greenhouse.io/snapchat/jobs/6404?#app'}
# company_list['aspera'] = {'name':'Aspera','description':'Aspera High-speed File Transfer Software that moves the world’s data at maximum speed, regardless of file size, transfer distance or network conditions ','links':'http://asperasoft.com/company/careers/'}
# company_list['asana'] = {'name':'Asana','description':'Asana is a web and mobile application designed to enable teamwork without email.','links':'https://asana.com/apply?job=Software+Engineering+Intern&id=18765914436573'}
# company_list['nest'] = {'name':'Nest Labs','description':'We reinvent unloved but important home products, like the thermostat and smoke alarm. The company focuses on delighting customers with simple, beautiful and thoughtful hardware, software and services. ','links':'http://hire.jobvite.com/CompanyJobs/Careers.aspx?k=Apply&c=qW69VfwQ&j=oS7wZfwe'}
# company_list['spokeo'] = {'name':'Spokeo','description':'Spokeo is a people search website that aggregates data from many online and offline sources.','links':'https://boards.greenhouse.io/spokeo/jobs/33554#.VF_V8fldWSo'}
# company_list['zillow'] = {'name':'Zillow', 'description':"Zillow is an online real estate database that was founded in 2005 and created by Rich Barton and Lloyd Frink, former Microsoft executives and founders of Microsoft spin-off Expedia. Spencer Rascoff is the current CEO of Zillow, Inc.", 'links':'http://www.zillow.com/jobs/apply?j=oeshZfwG'}
# company_list['tubemogul'] = {'name':'Tubemogul', 'description': "TubeMogul is a publicly traded enterprise software platform for digital video advertising. TubeMogul’s programmatic software platform leverages real-time bidding (RTB) technology to help major brands, advertising agencies, trading desks, and publishers advertise to global audiences using online video across multiple devices.", 'links':"https://boards.greenhouse.io/tubemogulinc/jobs/33121?#app"}
# company_list['thumbtack'] = {'name':'Thumbtack', 'description':"Thumbtack is a consumer service for finding and hiring local businesses, launched in December 2009. Thumbtack allows service providers and consumers to find each other and negotiate jobs online.", 'links':"https://boards.greenhouse.io/thumbtack/jobs/2570?#app"}
company_list['box'] = {'name':'Box', 'description':"Box Inc. (formerly Box.net) is an online file sharing and personal cloud content management service for businesses. The company adopted a freemium business model, and provides up to 10 GB of free storage for personal accounts.", 'links':"https://jobs.lever.co/box/c0aba64f-7d5d-4e52-b1eb-03460b0f34a6/apply"}
# company_list['splunk'] = {'name':'Splunk', 'description':"Splunk is an American multinational corporation headquartered in San Francisco, California, which produces software for searching, monitoring, and analyzing machine-generated big data, via a web-style interface.", 'links':"http://www.splunk.com/view/SP-CAAAGK3?jvi=ob8gZfwi"}
# company_list['pixar'] = {'name':'Pixar', 'description':"Pixar Animation Studios is an American computer animation film studio based in Emeryville, California. The studio is best known for its CGI-animated feature films created with PhotoRealistic RenderMan, its own implementation of the industry-standard RenderMan image-rendering application programming interface used to generate high-quality images.", 'links':'http://www.pixar.com/careers/available-internships#Pixar-Internships-StudioToolsResearch-1110'}
# company_list['ea'] = {'name':'EA', 'description':"Electronic Arts, Inc. (EA), also known as EA Games, is an American developer, marketer, publisher and distributor of video games headquartered in Redwood City, California, U.S. Founded and incorporated on May 28, 1982 by Trip Hawkins, the company was a pioneer of the early home computer games industry and was notable for promoting the designers and programmers responsible for its games.", 'links':"http://ea.avature.net/university"}
# company_list['facebook'] = {'name':'Facebook', 'description':"Facebook (formerly [thefacebook]) is an online social networking service headquartered in Menlo Park, California. Its name comes from a colloquialism for the directory given to students at some American universities.", 'links':"https://www.facebook.com/careers/resume?dept=interns&req=a0IA000000Cy2AKMAZ"}
# company_list['bloomberg'] = {'name':'Bloomberg', 'description':"Bloomberg L.P. is a privately held financial software, data and media company headquartered in New York City. Bloomberg L.P. was founded by Michael Bloomberg in 1981.", 'links':'http://jobs.bloomberg.com/talentcommunity/apply/81332300/?locale=en_US#tracked'}
# company_list['khan'] = {'name':"Khan Academy", 'description':'Khan Academy is a non-profit educational organization created in 2006 by educator Salman Khan to provide "a free, world-class education for anyone, anywhere.', 'links':"https://boards.greenhouse.io/khanacademy/jobs/15827#app"}
# company_list['mongodb'] = {'name':"MongoDB", 'description':"MongoDB is a cross-platform document-oriented database. Classified as a NoSQL database, MongoDB eschews the traditional table-based relational database structure in favor of JSON-like documents with dynamic schemas (MongoDB calls the format BSON), making the integration of data in certain types of applications easier and faster.", 'links':"http://hire.jobvite.com/CompanyJobs/Careers.aspx?k=Apply&c=qX79VfwS&j=oG2vZfwW"}
# company_list['spacex'] = {'name':"SpaceX", 'description':"Space Exploration Technologies Corporation (SpaceX) is a space transport services company headquartered in Hawthorne, California. It was founded in 2002 by former PayPal entrepreneur and Tesla Motors CEO Elon Musk.", 'links':"https://hire.jobvite.com/CompanyJobs/Careers.aspx?k=Apply&c=qz49Vfwr&j=obTMZfwz&nl=0"}
# company_list['square'] = {'name':"Square", 'description':"Square, Inc. is a financial services, merchant services aggregator and mobile payments company based in San Francisco, California. The company markets several software and hardware products and services, including Square Register and Square Order. The company was founded in 2009 by Jack Dorsey and Jim McKelvey and launched its first app and service in 2010.", 'links':"http://hire.jobvite.com/CompanyJobs/Careers.aspx?c=q8Z9VfwV&page=Apply&j=o2XdZfwV"}